server:
  port: 10010

spring:
  application:
    name: gateway   #服务名称
  cloud:
    nacos:
      server-addr: 192.168.0.120:80   #nacos地址
    gateway:
      routes:     #网关路由配置
        - id: user-service    #路由id，自定义，全局唯一即可
          #url: http://127.0.0.1:8081 #路由的目标地址，http就是固定地址
          uri: lb://userservice   #路由的目标地址，lb就是loadBalance 负载均衡，后面跟服务名称
          predicates:   #路由断言，也就是判断请求是否复合路由规则的条件
            - Path=/user/**    #这个是按路径匹配，只要/user开头就符合要求，多个路径按，隔开
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=name,xiaojian
#          filters:
#            - AddRequestHeader=name,xiaojian
